_target_: src.datamodules.plant_village_datamodule.PlantVillageDatamodule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
fraction_size: 1.0
fraction_end: False
train_val_test_split: [0.8, 0.05, 0.05]
num_workers: 8
pin_memory: True
